// generated source. do not edit.
#![allow(non_upper_case_globals, unused_macros, unused_imports)]
use crate::low::macros::*;

// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0 OR ISC

// ----------------------------------------------------------------------------
// Extend Montgomery reduce in 8-digit blocks, uses an extra storage to
// temporarily cache multiplied differences appearing in ADK.
// Results are stored in input-output buffer (z).
// k must be divisible by 8 and not smaller than 16.
// Inputs z[2*k], m[k], w;
// Outputs function return (extra result bit) and z[2*k]
// Temporary buffer m_precalc[12*(k/4-1)]
//
//    extern uint64_t bignum_emontredc_8n_cdiff(uint64_t k, uint64_t *z,
//                                              const uint64_t *m, uint64_t w,
//                                              uint64_t *m_precalc);
//
// Standard ARM ABI: X0 = k, X1 = z, X2 = m, X3 = w, X4 = m_precalc
//                   returns X0
// ----------------------------------------------------------------------------

/// Extend Montgomery reduce in 8-digit blocks, uses an extra storage to
///
/// temporarily cache multiplied differences appearing in ADK.
/// Results are stored in input-output buffer (z).
/// k must be divisible by 8 and not smaller than 16.
/// Inputs z[2*k], m[k], w;
/// Outputs function return (extra result bit) and z[2*k]
/// Temporary buffer m_precalc[12*(k/4-1)]
pub(crate) fn bignum_emontredc_8n_cdiff(
    z: &mut [u64],
    m: &[u64],
    w: u64,
    m_precalc: &mut [u64],
) -> u64 {
    let ret: u64;
    debug_assert!(z.len() == m.len() * 2);
    debug_assert!(z.len().is_multiple_of(8));
    debug_assert!(z.len() >= 32);
    debug_assert!(m_precalc.len() >= 12 * (m.len() / 4 - 1));
    // SAFETY: inline assembly. see [crate::low::inline_assembly_safety] for safety info.
    unsafe {
        core::arch::asm!(
        Q!("    sub             " "sp, sp, #0xa0"),
        Q!("    stp             " "x19, x20, [sp, #144]"),
        Q!("    stp             " "x21, x22, [sp, #128]"),
        Q!("    stp             " "x23, x24, [sp, #112]"),
        Q!("    stp             " "x25, x26, [sp, #96]"),
        Q!("    stp             " "x27, x28, [sp, #80]"),
        Q!("    stp             " "x29, x30, [sp, #64]"),
        Q!("    stp             " "d14, d15, [sp, #48]"),
        Q!("    stp             " "d12, d13, [sp, #32]"),
        Q!("    stp             " "d10, d11, [sp, #16]"),
        Q!("    stp             " "d8, d9, [sp]"),
        Q!("    sub             " "sp, sp, #0x60"),
        Q!("    sub             " "sp, sp, #0x20"),
        Q!("    lsr             " "x0, x0, #2"),
        Q!("    mov             " "x26, x0"),
        Q!("    subs            " "x12, x0, #0x1"),
        Q!("    b.cc            " Label!("Lbignum_emontredc_8n_cdiff_end", 2, After)),
        Q!("    mov             " "x24, x4"),
        Q!("    mov             " "x30, x4"),
        Q!("    mov             " "x25, x2"),
        Q!("    mov             " "x27, x12"),

        Q!(Label!("Lbignum_emontredc_8n_cdiff_precomp", 3) ":"),
        Q!("    ldp             " "x4, x5, [x2, #32] !"),
        Q!("    ldp             " "x6, x7, [x2, #16]"),
        Q!("    subs            " "x28, x5, x4"),
        Q!("    cneg            " "x28, x28, cc"),
        Q!("    csetm           " "x29, cc"),
        Q!("    stp             " "x28, x29, [x30]"),
        Q!("    subs            " "x28, x6, x4"),
        Q!("    cneg            " "x28, x28, cc"),
        Q!("    csetm           " "x29, cc"),
        Q!("    stp             " "x28, x29, [x30, #16]"),
        Q!("    subs            " "x28, x7, x4"),
        Q!("    cneg            " "x28, x28, cc"),
        Q!("    csetm           " "x29, cc"),
        Q!("    stp             " "x28, x29, [x30, #32]"),
        Q!("    subs            " "x28, x6, x5"),
        Q!("    cneg            " "x28, x28, cc"),
        Q!("    csetm           " "x29, cc"),
        Q!("    stp             " "x28, x29, [x30, #48]"),
        Q!("    subs            " "x28, x7, x5"),
        Q!("    cneg            " "x28, x28, cc"),
        Q!("    csetm           " "x29, cc"),
        Q!("    stp             " "x28, x29, [x30, #64]"),
        Q!("    subs            " "x28, x7, x6"),
        Q!("    cneg            " "x28, x28, cc"),
        Q!("    csetm           " "x29, cc"),
        Q!("    stp             " "x28, x29, [x30, #80]"),
        Q!("    add             " "x30, x30, #0x60"),
        Q!("    subs            " "x27, x27, #0x1"),
        Q!("    cbnz            " "x27, " Label!("Lbignum_emontredc_8n_cdiff_precomp", 3, Before)),
        Q!("    mov             " "x2, x25"),
        Q!("    mov             " "x30, x24"),
        Q!("    stp             " "x3, x30, [sp]"),
        Q!("    stp             " "x26, xzr, [sp, #16]"),
        Q!("    mov             " "x28, xzr"),
        Q!("    lsl             " "x0, x12, #5"),
        Q!("    movi            " "v29.2d, #0xffffffff"),

        Q!(Label!("Lbignum_emontredc_8n_cdiff_outerloop", 4) ":"),
        Q!("    ldp             " "x9, x13, [x1]"),
        Q!("    ldr             " "x3, [sp]"),
        Q!("    lsr             " "x27, x0, #5"),
        Q!("    sub             " "x27, x27, #0x1"),
        Q!("    ldp             " "x10, x12, [x1, #16]"),
        Q!("    ldp             " "x4, x15, [x2]"),
        Q!("    ldr             " "q1, [x2, #16]"),
        Q!("    mul             " "x11, x9, x3"),
        Q!("    uzp2            " "v18.4s, v1.4s, v1.4s"),
        Q!("    dup             " "v27.2d, x11"),
        Q!("    xtn             " "v13.2s, v1.2d"),
        Q!("    rev64           " "v9.4s, v1.4s"),
        Q!("    mul             " "x7, x11, x4"),
        Q!("    rev64           " "v2.4s, v1.4s"),
        Q!("    uzp2            " "v20.4s, v1.4s, v1.4s"),
        Q!("    mul             " "v31.4s, v9.4s, v27.4s"),
        Q!("    xtn             " "v14.2s, v1.2d"),
        Q!("    uzp2            " "v21.4s, v1.4s, v1.4s"),
        Q!("    umulh           " "x22, x11, x15"),
        Q!("    xtn             " "v17.2s, v27.2d"),
        Q!("    adds            " "x19, x9, x7"),
        Q!("    umull           " "v28.2d, v17.2s, v13.2s"),
        Q!("    umull           " "v26.2d, v17.2s, v18.2s"),
        Q!("    uaddlp          " "v8.2d, v31.4s"),
        Q!("    umulh           " "x8, x11, x4"),
        Q!("    shl             " "v7.2d, v8.2d, #32"),
        Q!("    uzp2            " "v30.4s, v27.4s, v27.4s"),
        Q!("    umlal           " "v7.2d, v17.2s, v13.2s"),
        Q!("    mul             " "x14, x11, x15"),
        Q!("    usra            " "v26.2d, v28.2d, #32"),
        Q!("    umull           " "v12.2d, v30.2s, v18.2s"),
        Q!("    mov             " "x24, v7.d[0]"),
        Q!("    adcs            " "x29, x13, x14"),
        Q!("    and             " "v4.16b, v26.16b, v29.16b"),
        Q!("    mov             " "x17, v7.d[1]"),
        Q!("    rev64           " "v27.4s, v1.4s"),
        Q!("    adcs            " "x5, x10, x24"),
        Q!("    umlal           " "v4.2d, v30.2s, v13.2s"),
        Q!("    usra            " "v12.2d, v26.2d, #32"),
        Q!("    adcs            " "x14, x12, x17"),
        Q!("    adc             " "x23, xzr, xzr"),
        Q!("    adds            " "x8, x29, x8"),
        Q!("    adcs            " "x7, x5, x22"),
        Q!("    mul             " "x25, x8, x3"),
        Q!("    usra            " "v12.2d, v4.2d, #32"),
        Q!("    dup             " "v8.2d, x25"),
        Q!("    stp             " "x11, x25, [x1]"),
        Q!("    mul             " "x22, x25, x4"),
        Q!("    mov             " "x16, v12.d[1]"),
        Q!("    ldr             " "q16, [x1]"),
        Q!("    mov             " "x21, v12.d[0]"),
        Q!("    mul             " "v31.4s, v27.4s, v8.4s"),
        Q!("    adcs            " "x20, x14, x21"),
        Q!("    xtn             " "v27.2s, v8.2d"),
        Q!("    adc             " "x10, x23, x16"),
        Q!("    subs            " "x14, x11, x25"),
        Q!("    rev64           " "v17.4s, v16.4s"),
        Q!("    cneg            " "x17, x14, cc"),
        Q!("    csetm           " "x26, cc"),
        Q!("    uaddlp          " "v26.2d, v31.4s"),
        Q!("    mul             " "x6, x25, x15"),
        Q!("    stp             " "x17, x26, [sp, #32]"),
        Q!("    umull           " "v24.2d, v27.2s, v14.2s"),
        Q!("    uzp2            " "v30.4s, v16.4s, v16.4s"),
        Q!("    shl             " "v4.2d, v26.2d, #32"),
        Q!("    uzp2            " "v5.4s, v8.4s, v8.4s"),
        Q!("    umulh           " "x17, x25, x4"),
        Q!("    umlal           " "v4.2d, v27.2s, v14.2s"),
        Q!("    umull           " "v8.2d, v27.2s, v21.2s"),
        Q!("    mov             " "x21, v4.d[0]"),
        Q!("    adds            " "x8, x8, x22"),
        Q!("    mov             " "x12, v4.d[1]"),
        Q!("    ldp             " "x23, x14, [x2, #16]"),
        Q!("    adcs            " "x29, x7, x6"),
        Q!("    umulh           " "x13, x25, x15"),
        Q!("    usra            " "v8.2d, v24.2d, #32"),
        Q!("    ldp             " "x8, x24, [x30, #16]"),
        Q!("    adcs            " "x9, x20, x21"),
        Q!("    ldr             " "q9, [x2, #32] !"),
        Q!("    xtn             " "v28.2s, v16.2d"),
        Q!("    adcs            " "x19, x10, x12"),
        Q!("    ldr             " "q13, [x2, #16]"),
        Q!("    umull           " "v18.2d, v5.2s, v21.2s"),
        Q!("    adc             " "x7, xzr, xzr"),
        Q!("    adds            " "x5, x29, x17"),
        Q!("    xtn             " "v21.2s, v1.2d"),
        Q!("    mul             " "x12, x5, x3"),
        Q!("    and             " "v4.16b, v8.16b, v29.16b"),
        Q!("    adcs            " "x21, x9, x13"),
        Q!("    uzp2            " "v31.4s, v9.4s, v9.4s"),
        Q!("    xtn             " "v23.2s, v9.2d"),
        Q!("    usra            " "v18.2d, v8.2d, #32"),
        Q!("    umlal           " "v4.2d, v5.2s, v14.2s"),
        Q!("    dup             " "v5.2d, x12"),
        Q!("    umull           " "v16.2d, v23.2s, v30.2s"),
        Q!("    umull           " "v1.2d, v23.2s, v28.2s"),
        Q!("    umulh           " "x29, x12, x15"),
        Q!("    umull           " "v8.2d, v31.2s, v30.2s"),
        Q!("    xtn             " "v24.2s, v13.2d"),
        Q!("    mul             " "v25.4s, v2.4s, v5.4s"),
        Q!("    usra            " "v18.2d, v4.2d, #32"),
        Q!("    xtn             " "v3.2s, v5.2d"),
        Q!("    uzp2            " "v19.4s, v5.4s, v5.4s"),
        Q!("    mul             " "x10, x12, x15"),
        Q!("    umull           " "v26.2d, v3.2s, v20.2s"),
        Q!("    mov             " "x22, v18.d[0]"),
        Q!("    umull           " "v10.2d, v3.2s, v21.2s"),
        Q!("    uaddlp          " "v11.2d, v25.4s"),
        Q!("    mov             " "x6, v18.d[1]"),
        Q!("    mul             " "x16, x12, x4"),
        Q!("    umull           " "v4.2d, v19.2s, v20.2s"),
        Q!("    usra            " "v16.2d, v1.2d, #32"),
        Q!("    adcs            " "x13, x19, x22"),
        Q!("    shl             " "v11.2d, v11.2d, #32"),
        Q!("    adc             " "x6, x7, x6"),
        Q!("    subs            " "x7, x11, x12"),
        Q!("    usra            " "v26.2d, v10.2d, #32"),
        Q!("    csetm           " "x26, cc"),
        Q!("    cneg            " "x20, x7, cc"),
        Q!("    subs            " "x19, x25, x12"),
        Q!("    umlal           " "v11.2d, v3.2s, v21.2s"),
        Q!("    cneg            " "x9, x19, cc"),
        Q!("    stp             " "x20, x26, [sp, #48]"),
        Q!("    umulh           " "x7, x12, x4"),
        Q!("    usra            " "v8.2d, v16.2d, #32"),
        Q!("    mul             " "v7.4s, v17.4s, v9.4s"),
        Q!("    csetm           " "x26, cc"),
        Q!("    adds            " "x19, x5, x16"),
        Q!("    and             " "v1.16b, v16.16b, v29.16b"),
        Q!("    adcs            " "x21, x21, x10"),
        Q!("    stp             " "x9, x26, [sp, #80]"),
        Q!("    ldp             " "x17, x20, [sp, #48]"),
        Q!("    usra            " "v4.2d, v26.2d, #32"),
        Q!("    and             " "v18.16b, v26.16b, v29.16b"),
        Q!("    umlal           " "v1.2d, v31.2s, v28.2s"),
        Q!("    mov             " "x22, v11.d[0]"),
        Q!("    mov             " "x16, v11.d[1]"),
        Q!("    umlal           " "v18.2d, v19.2s, v21.2s"),
        Q!("    adcs            " "x19, x13, x22"),
        Q!("    mul             " "x22, x17, x8"),
        Q!("    uaddlp          " "v5.2d, v7.4s"),
        Q!("    adcs            " "x13, x6, x16"),
        Q!("    usra            " "v8.2d, v1.2d, #32"),
        Q!("    adc             " "x9, xzr, xzr"),
        Q!("    adds            " "x5, x21, x7"),
        Q!("    usra            " "v4.2d, v18.2d, #32"),
        Q!("    adcs            " "x6, x19, x29"),
        Q!("    mul             " "x19, x5, x3"),
        Q!("    shl             " "v15.2d, v5.2d, #32"),
        Q!("    mov             " "x3, v8.d[1]"),
        Q!("    umlal           " "v15.2d, v23.2s, v28.2s"),
        Q!("    mov             " "x21, v4.d[0]"),
        Q!("    mul             " "x7, x19, x23"),
        Q!("    stp             " "x12, x19, [x1, #16]"),
        Q!("    mov             " "x10, v4.d[1]"),
        Q!("    ldr             " "q9, [x1, #16]"),
        Q!("    adcs            " "x13, x13, x21"),
        Q!("    mov             " "x21, v15.d[1]"),
        Q!("    mul             " "x16, x19, x4"),
        Q!("    adc             " "x9, x9, x10"),
        Q!("    subs            " "x29, x25, x19"),
        Q!("    csetm           " "x26, cc"),
        Q!("    cneg            " "x10, x29, cc"),
        Q!("    subs            " "x29, x12, x19"),
        Q!("    stp             " "x10, x26, [sp, #96]"),
        Q!("    uzp2            " "v18.4s, v9.4s, v9.4s"),
        Q!("    mul             " "x12, x19, x15"),
        Q!("    rev64           " "v20.4s, v9.4s"),
        Q!("    xtn             " "v19.2s, v9.2d"),
        Q!("    umull           " "v25.2d, v24.2s, v18.2s"),
        Q!("    csetm           " "x26, cc"),
        Q!("    umull           " "v14.2d, v24.2s, v19.2s"),
        Q!("    cneg            " "x29, x29, cc"),
        Q!("    umulh           " "x10, x19, x23"),
        Q!("    adds            " "x25, x5, x16"),
        Q!("    mul             " "v7.4s, v20.4s, v13.4s"),
        Q!("    adcs            " "x12, x6, x12"),
        Q!("    ldp             " "x6, x5, [sp, #32]"),
        Q!("    mov             " "x16, v8.d[0]"),
        Q!("    adcs            " "x25, x13, x7"),
        Q!("    stp             " "x29, x26, [sp, #112]"),
        Q!("    usra            " "v25.2d, v14.2d, #32"),
        Q!("    mul             " "x29, x19, x14"),
        Q!("    uzp2            " "v1.4s, v13.4s, v13.4s"),
        Q!("    uaddlp          " "v7.2d, v7.4s"),
        Q!("    umull           " "v0.2d, v1.2s, v18.2s"),
        Q!("    umulh           " "x13, x19, x4"),
        Q!("    and             " "v10.16b, v25.16b, v29.16b"),
        Q!("    shl             " "v13.2d, v7.2d, #32"),
        Q!("    adcs            " "x4, x9, x29"),
        Q!("    umlal           " "v10.2d, v1.2s, v19.2s"),
        Q!("    adc             " "x9, xzr, xzr"),
        Q!("    subs            " "x29, x11, x19"),
        Q!("    usra            " "v0.2d, v25.2d, #32"),
        Q!("    eor             " "x11, x20, x24"),
        Q!("    umulh           " "x15, x19, x15"),
        Q!("    umlal           " "v13.2d, v24.2s, v19.2s"),
        Q!("    cneg            " "x7, x29, cc"),
        Q!("    ldp             " "x20, x29, [x1, #32] !"),
        Q!("    csetm           " "x26, cc"),
        Q!("    usra            " "v0.2d, v10.2d, #32"),
        Q!("    umulh           " "x19, x19, x14"),
        Q!("    mov             " "x23, v13.d[1]"),
        Q!("    stp             " "x7, x26, [sp, #64]"),
        Q!("    adds            " "x12, x12, x13"),
        Q!("    adcs            " "x13, x25, x15"),
        Q!("    mov             " "x26, v0.d[0]"),
        Q!("    umulh           " "x8, x17, x8"),
        Q!("    adcs            " "x14, x4, x10"),
        Q!("    mov             " "x17, v13.d[0]"),
        Q!("    adc             " "x15, x9, x19"),
        Q!("    ldp             " "x24, x10, [x30], #96"),

        Q!(Label!("Lbignum_emontredc_8n_cdiff_maddloop_neon", 5) ":"),
        Q!("    ldr             " "q14, [x2, #32] !"),
        Q!("    ldr             " "q25, [x2, #16]"),
        Q!("    eor             " "x19, x5, x10"),
        Q!("    adds            " "x25, x21, x16"),
        Q!("    mov             " "x16, v0.d[1]"),
        Q!("    ldp             " "x4, x7, [x1, #16]"),
        Q!("    adcs            " "x21, x17, x3"),
        Q!("    eor             " "x22, x22, x11"),
        Q!("    adcs            " "x23, x23, x26"),
        Q!("    adc             " "x17, x16, xzr"),
        Q!("    adds            " "x16, x12, x20"),
        Q!("    mul             " "x5, x6, x24"),
        Q!("    xtn             " "v21.2s, v14.2d"),
        Q!("    xtn             " "v31.2s, v25.2d"),
        Q!("    adcs            " "x9, x13, x29"),
        Q!("    uzp2            " "v24.4s, v25.4s, v25.4s"),
        Q!("    mov             " "x29, v15.d[0]"),
        Q!("    adcs            " "x4, x14, x4"),
        Q!("    ldp             " "x10, x13, [sp, #112]"),
        Q!("    umull           " "v5.2d, v21.2s, v30.2s"),
        Q!("    umulh           " "x20, x6, x24"),
        Q!("    adcs            " "x24, x15, x7"),
        Q!("    ldp             " "x12, x7, [x30, #-16]"),
        Q!("    umull           " "v16.2d, v31.2s, v18.2s"),
        Q!("    adc             " "x6, xzr, xzr"),
        Q!("    adds            " "x14, x25, x29"),
        Q!("    umull           " "v13.2d, v21.2s, v28.2s"),
        Q!("    uzp2            " "v10.4s, v14.4s, v14.4s"),
        Q!("    eor             " "x15, x8, x11"),
        Q!("    adcs            " "x25, x21, x25"),
        Q!("    umull           " "v1.2d, v31.2s, v19.2s"),
        Q!("    adcs            " "x8, x23, x21"),
        Q!("    mul             " "v6.4s, v20.4s, v25.4s"),
        Q!("    eor             " "x7, x13, x7"),
        Q!("    adcs            " "x23, x17, x23"),
        Q!("    eor             " "x21, x5, x19"),
        Q!("    adc             " "x13, xzr, x17"),
        Q!("    adds            " "x17, x25, x29"),
        Q!("    umull           " "v0.2d, v24.2s, v18.2s"),
        Q!("    usra            " "v5.2d, v13.2d, #32"),
        Q!("    adcs            " "x5, x8, x14"),
        Q!("    umull           " "v2.2d, v10.2s, v30.2s"),
        Q!("    adcs            " "x25, x23, x25"),
        Q!("    usra            " "v16.2d, v1.2d, #32"),
        Q!("    adcs            " "x8, x13, x8"),
        Q!("    uaddlp          " "v13.2d, v6.4s"),
        Q!("    adcs            " "x23, xzr, x23"),
        Q!("    and             " "v7.16b, v5.16b, v29.16b"),
        Q!("    adc             " "x13, xzr, x13"),
        Q!("    adds            " "x29, x29, x16"),
        Q!("    mul             " "x16, x10, x12"),
        Q!("    usra            " "v2.2d, v5.2d, #32"),
        Q!("    adcs            " "x9, x14, x9"),
        Q!("    and             " "v25.16b, v16.16b, v29.16b"),
        Q!("    adcs            " "x17, x17, x4"),
        Q!("    umlal           " "v7.2d, v10.2s, v28.2s"),
        Q!("    umulh           " "x12, x10, x12"),
        Q!("    adcs            " "x10, x5, x24"),
        Q!("    usra            " "v0.2d, v16.2d, #32"),
        Q!("    eor             " "x5, x16, x7"),
        Q!("    ldp             " "x16, x14, [x30, #-32]"),
        Q!("    adcs            " "x6, x25, x6"),
        Q!("    shl             " "v16.2d, v13.2d, #32"),
        Q!("    eor             " "x24, x20, x19"),
        Q!("    adcs            " "x4, x8, xzr"),
        Q!("    ldp             " "x20, x25, [sp, #96]"),
        Q!("    umlal           " "v25.2d, v24.2s, v19.2s"),
        Q!("    adcs            " "x23, x23, xzr"),
        Q!("    usra            " "v2.2d, v7.2d, #32"),
        Q!("    umlal           " "v16.2d, v31.2s, v19.2s"),
        Q!("    adc             " "x8, x13, xzr"),
        Q!("    cmn             " "x7, #0x1"),
        Q!("    mul             " "v7.4s, v17.4s, v14.4s"),
        Q!("    adcs            " "x4, x4, x5"),
        Q!("    eor             " "x5, x12, x7"),
        Q!("    adcs            " "x23, x23, x5"),
        Q!("    mul             " "x12, x20, x16"),
        Q!("    adc             " "x5, x8, x7"),
        Q!("    cmn             " "x19, #0x1"),
        Q!("    adcs            " "x21, x9, x21"),
        Q!("    eor             " "x8, x25, x14"),
        Q!("    usra            " "v0.2d, v25.2d, #32"),
        Q!("    adcs            " "x13, x17, x24"),
        Q!("    stp             " "x29, x21, [x1]"),
        Q!("    umulh           " "x20, x20, x16"),
        Q!("    uaddlp          " "v10.2d, v7.4s"),
        Q!("    adcs            " "x17, x10, x19"),
        Q!("    mov             " "x3, v2.d[1]"),
        Q!("    ldp             " "x29, x24, [sp, #64]"),
        Q!("    adcs            " "x25, x6, x19"),
        Q!("    ldp             " "x6, x21, [x30, #-64]"),
        Q!("    eor             " "x10, x12, x8"),
        Q!("    adcs            " "x9, x4, x19"),
        Q!("    mov             " "x26, v0.d[0]"),
        Q!("    ldp             " "x4, x16, [x30, #-48]"),
        Q!("    adcs            " "x12, x23, x19"),
        Q!("    adc             " "x5, x5, x19"),
        Q!("    cmn             " "x8, #0x1"),
        Q!("    ldp             " "x7, x19, [sp, #80]"),
        Q!("    adcs            " "x14, x25, x10"),
        Q!("    mul             " "x25, x29, x6"),
        Q!("    eor             " "x20, x20, x8"),
        Q!("    adcs            " "x23, x9, x20"),
        Q!("    ldp             " "x9, x20, [sp, #48]"),
        Q!("    eor             " "x24, x24, x21"),
        Q!("    adcs            " "x12, x12, x8"),
        Q!("    adc             " "x10, x5, x8"),
        Q!("    cmn             " "x11, #0x1"),
        Q!("    umulh           " "x5, x29, x6"),
        Q!("    shl             " "v15.2d, v10.2d, #32"),
        Q!("    adcs            " "x8, x13, x22"),
        Q!("    eor             " "x13, x25, x24"),
        Q!("    adcs            " "x29, x17, x15"),
        Q!("    umlal           " "v15.2d, v21.2s, v28.2s"),
        Q!("    adcs            " "x22, x14, x11"),
        Q!("    mov             " "x17, v16.d[0]"),
        Q!("    adcs            " "x21, x23, x11"),
        Q!("    mul             " "x23, x7, x4"),
        Q!("    adcs            " "x14, x12, x11"),
        Q!("    eor             " "x12, x19, x16"),
        Q!("    mov             " "x16, v2.d[0]"),
        Q!("    adc             " "x15, x10, x11"),
        Q!("    cmn             " "x24, #0x1"),
        Q!("    eor             " "x19, x5, x24"),
        Q!("    adcs            " "x11, x29, x13"),
        Q!("    umulh           " "x29, x7, x4"),
        Q!("    adcs            " "x13, x22, x19"),
        Q!("    ldp             " "x6, x5, [sp, #32]"),
        Q!("    ldp             " "x7, x25, [x30, #16]"),
        Q!("    adcs            " "x19, x21, x24"),
        Q!("    mov             " "x21, v15.d[1]"),
        Q!("    eor             " "x22, x23, x12"),
        Q!("    adcs            " "x14, x14, x24"),
        Q!("    mov             " "x23, v16.d[1]"),
        Q!("    adc             " "x15, x15, x24"),
        Q!("    cmn             " "x12, #0x1"),
        Q!("    ldp             " "x24, x10, [x30], #96"),
        Q!("    adcs            " "x11, x11, x22"),
        Q!("    mul             " "x22, x9, x7"),
        Q!("    eor             " "x4, x29, x12"),
        Q!("    adcs            " "x4, x13, x4"),
        Q!("    stp             " "x8, x11, [x1, #16]"),
        Q!("    adcs            " "x13, x19, x12"),
        Q!("    eor             " "x11, x20, x25"),
        Q!("    ldp             " "x20, x29, [x1, #32] !"),
        Q!("    adcs            " "x14, x14, x12"),
        Q!("    adc             " "x15, x15, x12"),
        Q!("    mov             " "x12, x4"),
        Q!("    umulh           " "x8, x9, x7"),
        Q!("    sub             " "x27, x27, #0x1"),
        Q!("    cbnz            " "x27, " Label!("Lbignum_emontredc_8n_cdiff_maddloop_neon", 5, Before)),

        Q!(Label!("Lbignum_emontredc_8n_cdiff_inner_loop_postamble", 6) ":"),
        Q!("    umulh           " "x19, x6, x24"),
        Q!("    ldp             " "x7, x9, [sp, #112]"),
        Q!("    adds            " "x4, x21, x16"),
        Q!("    mov             " "x25, v0.d[1]"),
        Q!("    eor             " "x5, x5, x10"),
        Q!("    adcs            " "x17, x17, x3"),
        Q!("    ldp             " "x16, x10, [x1, #16]"),
        Q!("    adcs            " "x21, x23, x26"),
        Q!("    eor             " "x8, x8, x11"),
        Q!("    adc             " "x23, x25, xzr"),
        Q!("    adds            " "x20, x12, x20"),
        Q!("    adcs            " "x12, x13, x29"),
        Q!("    mov             " "x25, v15.d[0]"),
        Q!("    adcs            " "x13, x14, x16"),
        Q!("    eor             " "x16, x19, x5"),
        Q!("    adcs            " "x29, x15, x10"),
        Q!("    ldp             " "x14, x19, [x30, #-16]"),
        Q!("    mul             " "x15, x6, x24"),
        Q!("    adc             " "x24, xzr, xzr"),
        Q!("    adds            " "x6, x4, x25"),
        Q!("    adcs            " "x10, x17, x4"),
        Q!("    eor             " "x4, x22, x11"),
        Q!("    adcs            " "x17, x21, x17"),
        Q!("    eor             " "x22, x9, x19"),
        Q!("    adcs            " "x9, x23, x21"),
        Q!("    adc             " "x21, xzr, x23"),
        Q!("    adds            " "x23, x10, x25"),
        Q!("    eor             " "x15, x15, x5"),
        Q!("    adcs            " "x19, x17, x6"),
        Q!("    ldp             " "x26, xzr, [sp, #16]"),
        Q!("    sub             " "x2, x2, x0"),
        Q!("    adcs            " "x10, x9, x10"),
        Q!("    adcs            " "x17, x21, x17"),
        Q!("    adcs            " "x9, xzr, x9"),
        Q!("    adc             " "x21, xzr, x21"),
        Q!("    adds            " "x25, x25, x20"),
        Q!("    mul             " "x20, x7, x14"),
        Q!("    adcs            " "x6, x6, x12"),
        Q!("    adcs            " "x23, x23, x13"),
        Q!("    adcs            " "x13, x19, x29"),
        Q!("    umulh           " "x19, x7, x14"),
        Q!("    ldp             " "x14, x29, [x30, #-32]"),
        Q!("    adcs            " "x10, x10, x24"),
        Q!("    ldp             " "x12, x7, [sp, #96]"),
        Q!("    adcs            " "x17, x17, xzr"),
        Q!("    adcs            " "x24, x9, xzr"),
        Q!("    adc             " "x9, x21, xzr"),
        Q!("    cmn             " "x22, #0x1"),
        Q!("    eor             " "x21, x20, x22"),
        Q!("    adcs            " "x20, x17, x21"),
        Q!("    eor             " "x17, x19, x22"),
        Q!("    mul             " "x19, x12, x14"),
        Q!("    eor             " "x29, x7, x29"),
        Q!("    adcs            " "x17, x24, x17"),
        Q!("    adc             " "x9, x9, x22"),
        Q!("    cmn             " "x5, #0x1"),
        Q!("    umulh           " "x21, x12, x14"),
        Q!("    ldp             " "x14, x24, [sp, #64]"),
        Q!("    adcs            " "x6, x6, x15"),
        Q!("    adcs            " "x7, x23, x16"),
        Q!("    ldp             " "x15, x12, [x30, #-64]"),
        Q!("    eor             " "x19, x19, x29"),
        Q!("    adcs            " "x13, x13, x5"),
        Q!("    stp             " "x25, x6, [x1]"),
        Q!("    adcs            " "x16, x10, x5"),
        Q!("    ldp             " "x10, x6, [x30, #-48]"),
        Q!("    adcs            " "x23, x20, x5"),
        Q!("    adcs            " "x25, x17, x5"),
        Q!("    umulh           " "x30, x14, x15"),
        Q!("    ldp             " "x17, x22, [sp, #80]"),
        Q!("    adc             " "x9, x9, x5"),
        Q!("    cmn             " "x29, #0x1"),
        Q!("    eor             " "x21, x21, x29"),
        Q!("    adcs            " "x16, x16, x19"),
        Q!("    adcs            " "x5, x23, x21"),
        Q!("    eor             " "x23, x24, x12"),
        Q!("    mul             " "x12, x17, x10"),
        Q!("    adcs            " "x19, x25, x29"),
        Q!("    adc             " "x29, x9, x29"),
        Q!("    cmn             " "x11, #0x1"),
        Q!("    adcs            " "x7, x7, x4"),
        Q!("    adcs            " "x21, x13, x8"),
        Q!("    mul             " "x4, x14, x15"),
        Q!("    eor             " "x9, x30, x23"),
        Q!("    adcs            " "x30, x16, x11"),
        Q!("    adcs            " "x24, x5, x11"),
        Q!("    adcs            " "x16, x19, x11"),
        Q!("    adc             " "x19, x29, x11"),
        Q!("    cmn             " "x23, #0x1"),
        Q!("    eor             " "x8, x4, x23"),
        Q!("    adcs            " "x4, x21, x8"),
        Q!("    umulh           " "x21, x17, x10"),
        Q!("    adcs            " "x8, x30, x9"),
        Q!("    ldp             " "x10, x30, [x1, #32]"),
        Q!("    adcs            " "x25, x24, x23"),
        Q!("    eor             " "x11, x22, x6"),
        Q!("    adcs            " "x22, x16, x23"),
        Q!("    eor             " "x5, x12, x11"),
        Q!("    adc             " "x29, x19, x23"),
        Q!("    cmn             " "x11, #0x1"),
        Q!("    eor             " "x14, x21, x11"),
        Q!("    adcs            " "x9, x4, x5"),
        Q!("    stp             " "x7, x9, [x1, #16]"),
        Q!("    adcs            " "x9, x8, x14"),
        Q!("    adcs            " "x19, x25, x11"),
        Q!("    ldp             " "x8, x21, [x1, #48]"),
        Q!("    mov             " "x24, x9"),
        Q!("    adcs            " "x5, x22, x11"),
        Q!("    adc             " "x16, x29, x11"),
        Q!("    cmn             " "x28, x28"),
        Q!("    adcs            " "x17, x10, x24"),
        Q!("    adcs            " "x14, x30, x19"),
        Q!("    ldr             " "x30, [sp, #8]"),
        Q!("    adcs            " "x8, x8, x5"),
        Q!("    stp             " "x17, x14, [x1, #32]"),
        Q!("    adcs            " "x9, x21, x16"),
        Q!("    csetm           " "x28, cs"),
        Q!("    stp             " "x8, x9, [x1, #48]"),
        Q!("    sub             " "x26, x26, #0x1"),
        Q!("    sub             " "x1, x1, x0"),
        Q!("    stp             " "x26, xzr, [sp, #16]"),
        Q!("    add             " "x1, x1, #0x20"),

        Q!(Label!("Lbignum_emontredc_8n_cdiff_outer_loop_end", 7) ":"),
        Q!("    cbnz            " "x26, " Label!("Lbignum_emontredc_8n_cdiff_outerloop", 4, Before)),
        Q!("    neg             " "x0, x28"),

        Q!(Label!("Lbignum_emontredc_8n_cdiff_end", 2) ":"),
        Q!("    add             " "sp, sp, #0x20"),
        Q!("    add             " "sp, sp, #0x60"),
        Q!("    ldp             " "d8, d9, [sp]"),
        Q!("    ldp             " "d10, d11, [sp, #16]"),
        Q!("    ldp             " "d12, d13, [sp, #32]"),
        Q!("    ldp             " "d14, d15, [sp, #48]"),
        Q!("    ldp             " "x29, x30, [sp, #64]"),
        Q!("    ldp             " "x27, x28, [sp, #80]"),
        Q!("    ldp             " "x25, x26, [sp, #96]"),
        Q!("    ldp             " "x23, x24, [sp, #112]"),
        Q!("    ldp             " "x21, x22, [sp, #128]"),
        Q!("    ldp             " "x19, x20, [sp, #144]"),
        Q!("    add             " "sp, sp, #0xa0"),
        inout("x0") m.len() => ret,
        inout("x1") z.as_mut_ptr() => _,
        inout("x2") m.as_ptr() => _,
        inout("x3") w => _,
        inout("x4") m_precalc.as_mut_ptr() => _,
        // clobbers
        out("v0") _,
        out("v1") _,
        out("v10") _,
        out("v11") _,
        out("v12") _,
        out("v13") _,
        out("v14") _,
        out("v15") _,
        out("v16") _,
        out("v17") _,
        out("v18") _,
        out("v19") _,
        out("v2") _,
        out("v20") _,
        out("v21") _,
        out("v23") _,
        out("v24") _,
        out("v25") _,
        out("v26") _,
        out("v27") _,
        out("v28") _,
        out("v29") _,
        out("v3") _,
        out("v30") _,
        out("v31") _,
        out("v4") _,
        out("v5") _,
        out("v6") _,
        out("v7") _,
        out("v8") _,
        out("v9") _,
        out("x10") _,
        out("x11") _,
        out("x12") _,
        out("x13") _,
        out("x14") _,
        out("x15") _,
        out("x16") _,
        out("x17") _,
        out("x20") _,
        out("x21") _,
        out("x22") _,
        out("x23") _,
        out("x24") _,
        out("x25") _,
        out("x26") _,
        out("x27") _,
        out("x28") _,
        out("x30") _,
        out("x5") _,
        out("x6") _,
        out("x7") _,
        out("x8") _,
        out("x9") _,
            )
    };
    ret
}
